### ISSUE TITLE
statistics page not showing actual statistics data

### ISSUE THREAD

**Issue by yankovs** [fkie-cad/mcritweb#25]
Hey!

Maybe an issue on my part, but I double checked that I'm following the docker-mcrit deployment yet the page still looks like this:
![image](https://github.com/fkie-cad/mcritweb/assets/49753115/e23e99c7-f515-44e3-bb27-81db8394fcc7)

**Comment by danielplohmann** [comment]
Ah, looks like this is an issue with `mcrit` with a missing field, due to the recent introduction of the DB timestamp:
```
mcrit-server    | 2024-01-09 10:23:40 [FALCON] [ERROR] GET /status?with_pichash=True => Traceback (most recent call last):
mcrit-server    |   File "falcon/app.py", line 365, in falcon.app.App.__call__
mcrit-server    |   File "/opt/mcrit/mcrit/server/utils.py", line 51, in wrapper
mcrit-server    |     func(*args, **kwargs)
mcrit-server    |   File "/opt/mcrit/mcrit/server/StatusResource.py", line 24, in on_get_status
mcrit-server    |     resp.data = jsonify({"status": "successful", "data": self.index.getStatus(with_pichash=with_pichash)})
mcrit-server    |   File "/opt/mcrit/mcrit/index/MinHashIndex.py", line 403, in getStatus
mcrit-server    |     storage_stats = self._storage.getStats(with_pichash=with_pichash)
mcrit-server    |   File "/opt/mcrit/mcrit/storage/MongoDbStorage.py", line 1039, in getStats
mcrit-server    |     "db_timestamp": self._convertDatetimeToString(self._getDbTimestamp()),
mcrit-server    |   File "/opt/mcrit/mcrit/storage/MongoDbStorage.py", line 285, in _getDbTimestamp
mcrit-server    |     return result["db_timestamp"]
mcrit-server    | KeyError: 'db_timestamp'
```
that means, if you add a single sample or do another real modification to the MCRIT db (not query), it should work again (at least it does for me).

I'll add some error handling for that. 
thanks for the pointer!

**Comment by danielplohmann** [comment]
fixed.
