### ISSUE TITLE
Possible regression: CFG view of functions

### ISSUE THREAD

**Issue by yankovs** [fkie-cad/mcritweb#30]
Hey! :)

We have noticed that for some samples (old ones from our testing), the function CFG view is empty:
![image](https://github.com/fkie-cad/mcritweb/assets/49753115/dccfc3ae-3b2b-4867-8f66-a2d2204a22c7)
and actually we get a 500 response on the request for the graph:
![image](https://github.com/fkie-cad/mcritweb/assets/49753115/bab29f26-f3e0-4110-a269-90dbebdcdb7c)

The actual exception thrown in mcritweb is:
```python3
mcritweb  | Traceback (most recent call last):
mcritweb  |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2529, in wsgi_app
mcritweb  |     response = self.full_dispatch_request()
mcritweb  |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1825, in full_dispatch_request
mcritweb  |     rv = self.handle_user_exception(e)
mcritweb  |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1823, in full_dispatch_request
mcritweb  |     rv = self.dispatch_request()
mcritweb  |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1799, in dispatch_request
mcritweb  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
mcritweb  |   File "/opt/mcritweb/mcritweb/views/authentication.py", line 204, in wrapped_view
mcritweb  |     return view(**kwargs)
mcritweb  |   File "/opt/mcritweb/mcritweb/views/utility.py", line 40, in wrapped_view
mcritweb  |     return view(**kwargs)
mcritweb  |   File "/opt/mcritweb/mcritweb/views/explore.py", line 279, in fetchDotGraph
mcritweb  |     smda_function = function_entry.toSmdaFunction()
mcritweb  |   File "/usr/local/lib/python3.8/dist-packages/mcrit/storage/FunctionEntry.py", line 75, in toSmdaFunction
mcritweb  |     return SmdaFunction.fromDict(self.xcfg, binary_info=binary_info)
mcritweb  |   File "/usr/local/lib/python3.8/dist-packages/smda/common/SmdaFunction.py", line 227, in fromDict
mcritweb  |     smda_function.stringrefs = {addr: string.decode("utf-8") for addr, string in function_dict["stringrefs"].items()} if "stringrefs" in function_dict["stringrefs"] else {}
mcritweb  | KeyError: 'stringrefs'
```
and the function that caused this looks like this in the functions collections:
```
[
  {
    _id: ObjectId('65268c10e4946258ce084a24'),
    architecture: 'intel',
    binweight: 172,
    family_id: 1,
    function_id: 92,
    function_name: 'runtime.alginit',
    function_labels: [
      {
        function_label: 'runtime.alginit',
        username: 'anonymous',
        timestamp: '2023-09-04T11:49:01'
      }
    ],
    matches: {},
    minhash: '5599de669564229eb12a4bb83d27bfbd3d18f26d9aaae88f4bbd233c4aa4170f2691a76126dee971c9505045f5b3b220d68c3393bdfbe152ef32517e0a417348',
    minhash_shingle_composition: {},
    num_blocks: 7,
    num_instructions: 36,
    offset: 4207824,
    sample_id: 0,
    _pichash: '0x16c41b3c270cf958',
    _picblockhashes: [
      {
        offset: 4207824,
        length: 4,
        size: 22,
        hash: '0xf28c0740165da14e'
      },
      {
        offset: 4207846,
        length: 4,
        size: 14,
        hash: '0x7625171616acfba3'
      },
      {
        offset: 4207882,
        length: 9,
        size: 42,
        hash: '0x7fe0a2bff2008813'
      },
      {
        offset: 4207924,
        length: 11,
        size: 62,
        hash: '0x9897a96147ea0d'
      }
    ],
    _xcfg: '{"offset": 4207824, "blocks": {"4207824": [[4207824, "648b0d14000000", "mov", "ecx, dword ptr fs:[0x14]"], [4207831, "8b8900000000", "mov", "ecx, dword ptr [ecx]"], [4207837, "3b6108", "cmp", "esp, dword ptr [ecx + 8]"], [4207840, "0f868c000000", "jbe", "0x403572"]], "4207846": [[4207846, "83ec0c", "sub", "esp, 0xc"], [4207849, "0fb605a0318f00", "movzx", "eax, byte ptr [0x8f31a0]"], [4207856, "84c0", "test", "al, al"], [4207858, "7440", "je", "0x403534"]], "4207860": [[4207860, "0fb605ad318f00", "movzx", "eax, byte ptr [0x8f31ad]"], [4207867, "84c0", "test", "al, al"], [4207869, "7435", "je", "0x403534"]], "4207871": [[4207871, "0fb605ae318f00", "movzx", "eax, byte ptr [0x8f31ae]"], [4207878, "84c0", "test", "al, al"], [4207880, "742a", "je", "0x403534"]], "4207882": [[4207882, "90", "nop", ""], [4207883, "c605a0298f0001", "mov", "byte ptr [0x8f29a0], 1"], [4207890, "8d05802e8f00", "lea", "eax, [0x8f2e80]"], [4207896, "890424", "mov", "dword ptr [esp], eax"], [4207899, "c744240440000000", "mov", "dword ptr [esp + 4], 0x40"], [4207907, "c744240840000000", "mov", "dword ptr [esp + 8], 0x40"], [4207915, "e860fa0200", "call", "0x432f90"], [4207920, "83c40c", "add", "esp, 0xc"], [4207923, "c3", "ret", ""]], "4207924": [[4207924, "8d05102d8f00", "lea", "eax, [0x8f2d10]"], [4207930, "890424", "mov", "dword ptr [esp], eax"], [4207933, "c744240410000000", "mov", "dword ptr [esp + 4], 0x10"], [4207941, "c744240810000000", "mov", "dword ptr [esp + 8], 0x10"], [4207949, "e83efa0200", "call", "0x432f90"], [4207954, "830d102d8f0001", "or", "dword ptr [0x8f2d10], 1"], [4207961, "830d142d8f0001", "or", "dword ptr [0x8f2d14], 1"], [4207968, "830d182d8f0001", "or", "dword ptr [0x8f2d18], 1"], [4207975, "830d1c2d8f0001", "or", "dword ptr [0x8f2d1c], 1"], [4207982, "83c40c", "add", "esp, 0xc"], [4207985, "c3", "ret", ""]], "4207986": [[4207986, "e8390e0600", "call", "0x4643b0"], [4207991, "e954ffffff", "jmp", "0x4034d0"]]}, "apirefs": {}, "blockrefs": {"4207824": [4207846, 4207986], "4207846": [4207860, 4207924], "4207860": [4207871, 4207924], "4207871": [4207882, 4207924], "4207986": [4207824]}, "inrefs": [4207991, 4434909], "outrefs": {"4207915": [4403088], "4207949": [4403088], "4207986": [4604848], "4207991": [4207824]}, "is_exported": false, "metadata": {"binweight": 172.0, "characteristics": "is-al-r--f-", "confidence": 0.5, "function_name": "runtime.alginit", "pic_hash": 11572652813552541120, "nesting_depth": 4, "strongly_connected_components": [[4207882], [4207924], [4207871], [4207860], [4207846], [4207986, 4207824]], "tfidf": 0.396}}'
  }
]
```

What I think is happening, is some sort of SMDA update regression but I'm not really sure.

**Comment by danielplohmann** [comment]
Yeah, same issues for why your test in the PR failed in MCRIT. :disappointed: 
But! I have just pushed SMDA 1.13.19 which should fix this issue for both cases. 
I will now incorporate your PR in MCRIT, then run tests to ensure that this works indeed across all locations where its used and push/update all mcrit tags + docker.

**Comment by danielplohmann** [comment]
alright, after updating to mcrit v1.3.13, this should work again, please quickly report if that's the case and we can likely close the issue.
